name: global checks

on: pull_request

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "hello world!"
          set
          python -c "import sys; print(sys.version)"
 
