name: global checks

on: pull_request

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: devrev/jano-gh-workflow
          path: ../global-checks-tooling
      - run: |
          set -x
          git status
          git branch -a
          pwd
          echo ${{ secrets.SNYK_TOKEN }}
          git rev-parse HEAD
          git log --format='%ae' ${{github.event.pull_request.base.sha}}..${{github.event.pull_request.head.sha}}
          python -c "import sys; print(sys.version)"
 
