name: global checks

on: pull_request

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4    
      - run: |
          echo "*** git status"
          git status
          echo "*** head"
          git rev-parse HEAD
          echo "*** set"
          set
          echo "*** get emails"
          git log --format='%ae' ${{github.event.pull_request.base.sha}}..${{github.event.pull_request.head.sha}}
          python -c "import sys; print(sys.version)"
 
