name: Reusable workflow example

on:
  workflow_call:
    inputs:
      config-path:
        required: false
        type: string
    secrets:
      token:
        required: false

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "hello world!"
          set

